# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ActionDispatch::Routing::Mapper; end
module ActionMailer::Base::Mail::Message; end
module ActiveSupport::ActionController::Base; end
module Gem::SilentUI; end
